swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions:
    get:
      tags:
        - User Transactions
      summary: Transactions of the month.
      description: API for all user transactions of the current month.
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: integer
          in: path
          name: id
          description: User ID for the account transactions
          required: true
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions/{transactionsId}:
    get:
      tags:
        - User Transactions
      summary: A detailed transaction
      description: API for getting one detailed transaction
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: integer
          in: path
          name: id
          description: User ID for the account transactions
          required: true
        - type: integer
          in: path
          name: transactionsId
          description: User transactions Id
          required: true
      responses:
        '200':
          description: Detailed transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions/{transactionsId}/category:
    put:
      tags:
        - User Transactions
      summary: Update a category from a transaction
      description: API for updating a category from a detailed transaction
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: integer
          in: path
          name: id
          description: User ID for the account transactions
          required: true
        - type: integer
          in: path
          name: transactionsId
          description: User transactions Id
          required: true
        - in: body
          name: body
          description: Update category detailed transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionsUpdateCategory'
      produces:
        - application/json
      responses:
        '200':
          description: Category from detailed transaction updated successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions/{transactionsId}/notes:
    post:
      tags:
        - User Transactions
      summary: Adding a notes from a transaction
      description: API for adding a notes from a detailed transaction
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: integer
          in: path
          name: id
          description: User ID for the account transactions
          required: true
        - type: integer
          in: path
          name: transactionsId
          description: User transactions Id
          required: true
        - in: body
          name: body
          description: Add notes detailed transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionsAddNotes'
      produces:
        - application/json
      responses:
        '200':
          description: Notes from detailed transaction added successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
  /user/accounts/{id}/transactions/{transactionsId}/notes/{notesId}:
    delete:
      tags:
        - User Transactions
      summary: Delete a notes from a transaction
      description: API for deleting a notes from a detailed transaction
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: integer
          in: path
          name: id
          description: User ID for the account transactions
          required: true
        - type: integer
          in: path
          name: transactionsId
          description: User transactions Id
          required: true
        - in: body
          name: body
          description: Add notes detailed transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionsDeleteNotes'
        - type: integer
          in: path
          name: notesId
          description: ID Notes detailed transaction
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Notes from a detailed transaction deleted successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: object
    properties:
      transactionsId:
        type: integer
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      transaction:
        type: string
      category:
        type: string
      notes:
        type: string
  TransactionsUpdateCategory:
    type: object
    properties:
      category:
        type: string
  TransactionsAddNotes:
    type: object
    properties: 
      notes: 
        type: string
  TransactionsDeleteNotes:
    type: object
    properties: 
      notesId: 
        type: integer